on:
  workflow_dispatch:

name: Source Upload

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ScratchAddons/website-i18n
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-scratchaddons-website-i18n-transifex
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Execute script
        run: |
          export TX_TOKEN=${{ secrets.TX_TOKEN }}
          pip install transifex-client
          tx push --source --use-git-timestamps --skip