on:
  workflow_dispatch:

name: Source Upload

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ScratchAddons/website-i18n
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-scratchaddons-website-i18n-transifex
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Execute script
        run: |
          echo Running...
          wget https://github.com/transifex/cli/releases/download/v1.0.0/tx-linux-amd64.tar.gz -O ${RUNNER_TEMP}/tx.tar.gz
          tar -zxvf ${RUNNER_TEMP}/tx.tar.gz -C ${RUNNER_TEMP} tx
          chmod -x tx
          alias tx='${RUNNER_TEMP}/tx'
          tx push --source --use-git-timestamps --skip
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}